### ISSUE TITLE
Take into account Play 2.4 Dependency Injection feature

### ISSUE THREAD

**Issue by AgileSpirit** [prismicio/scala-play-starter#7]
It would be great to have an example of how to integrate and use new Play 2.4 DI mechanism (cf. https://www.playframework.com/documentation/2.4.x/ScalaDependencyInjection)

**Comment by erwan** [comment]
Basically we're trying to keep the starter kits are simple as possible.

Where do you think dependency injection can be useful for this project?

**Comment by AgileSpirit** [comment]
Ok, I did not understand. You are right. I close the issue. :-)
